// <auto-generated />
using System;
using DAL.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DAL.Migrations
{
    [DbContext(typeof(MyDbContext))]
    partial class MyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DAL.Entity.Dormitory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("FloorsNumber")
                        .HasColumnType("int");

                    b.Property<string>("Manager")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Number")
                        .HasColumnType("int");

                    b.Property<int?>("RoomsNumber")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Year")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("dormitories");
                });

            modelBuilder.Entity("DAL.Entity.Furniture", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Item")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RoomId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Year")
                        .HasColumnType("datetime2");

                    b.Property<long?>("code")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.ToTable("furnitures");
                });

            modelBuilder.Entity("DAL.Entity.Inmate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RoomId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("isPaid")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.ToTable("inmates");
                });

            modelBuilder.Entity("DAL.Entity.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BedsNumder")
                        .HasColumnType("int");

                    b.Property<int>("DormintoryId")
                        .HasColumnType("int");

                    b.Property<int?>("DormitoryId")
                        .HasColumnType("int");

                    b.Property<int?>("Numder")
                        .HasColumnType("int");

                    b.Property<double?>("Payment")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("DormitoryId");

                    b.ToTable("rooms");
                });

            modelBuilder.Entity("DAL.Entity.Furniture", b =>
                {
                    b.HasOne("DAL.Entity.Room", null)
                        .WithMany("Furnitures")
                        .HasForeignKey("RoomId");
                });

            modelBuilder.Entity("DAL.Entity.Inmate", b =>
                {
                    b.HasOne("DAL.Entity.Room", null)
                        .WithMany("Inmates")
                        .HasForeignKey("RoomId");
                });

            modelBuilder.Entity("DAL.Entity.Room", b =>
                {
                    b.HasOne("DAL.Entity.Dormitory", null)
                        .WithMany("Rooms")
                        .HasForeignKey("DormitoryId");
                });

            modelBuilder.Entity("DAL.Entity.Dormitory", b =>
                {
                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("DAL.Entity.Room", b =>
                {
                    b.Navigation("Furnitures");

                    b.Navigation("Inmates");
                });
#pragma warning restore 612, 618
        }
    }
}
